---
title: "R Notebook"
output: html_notebook
---
2.2.1
```{r}
mul_15_add4 <- function(x){
  xr <- x*15+4
  return(xr)
}
```
```{r}
x <- c(1:3)
mul_15_add4(x)
```
2.2.2
```{r}
make_sound <- function(sound){
  sound_r <- " "
  sound_b <- c("goose", "duck", "pigeon")
  for (i in 1:length(sound)){
    if(sound[i] %in% sound_b){
        sound_r[i] <- "bird"
      } else{
        sound_r[i] <- "no bird"
      }
  }
  
  return(sound_r)
}
```

```{r}
make_sound(c("goose", "apple", "5", "seagull"))
```

2.2.3
```{r}
mul_10 <- function(nx){
  r_nx <- " "
  
  for(i in 1:length(nx)){
    rnx <- as.numeric(nx[i])
    ifelse(is.na(rnx)==TRUE, r_nx[i] <- "invalid input", r_nx[i] <- as.character(rnx*10))    
  }
  return(r_nx)
}
```

```{r}
mul_10(c("2", "5.3", "x", "7"))
```
2.3.1
```{r}
size <- c(13, 15, 10, 8, 22)
ifelse(size <= 10, "Small", "Big")
```

2.3.2
```{r}
fruit <- c("apple", "apple", "banana", "cherry", "cherry")
dplyr::recode(fruit, "apple" = "alpaca", "banana" = "bonobo", "cherry" = "chipmunk")
```

2.3.3
```{r}
wife_age <- c(29L, 30L, 36L, 31L, 22L)
husband_age <- c(28L, 35L, 32L, 31L, 29L)
dplyr::case_when(
  wife_age > husband_age ~ "Wife older",
  wife_age < husband_age ~ "Husband older",
  TRUE                   ~ "Same age"
)
```

2.4
```{r}
my_list <- list(
  4,
  "apple",
  10.5,
  c("is", "an", "apple"),
  "apple",
  c("i", "like", "apples"),
  8
)

```
2.4.1
```{r}
for(i_my_list in 1:length(my_list)){
  if(is.numeric(my_list[[i_my_list]]) != TRUE){
    print(my_list[[i_my_list]])
  }
}
```
2.4.2
```{r}
for(i_my_list in 1:length(my_list)){
  if(is.numeric(my_list[[i_my_list]]) != TRUE){
    if(length(my_list[[i_my_list]]) > 1){
      print(paste(my_list[[i_my_list]], collapse = ' '))
    }else{
      print(my_list[[i_my_list]])
    }
  }
}
```

Extension
3.1
```{r}
x <- 12
matriz <- matrix( nrow = x, ncol = x)
for(i in 1:x){
  for(j in 1:x){
    matriz[i,j] <- i*j
  }
}

```

3.2
```{r}
art_vec <- c("1 | ***", "2 | *", "3 | *******", "4 | ****", "5 | **")
cat(art_vec, sep = "\n")
```

3.3
```{r}
numberx <- 300
guessed <- FALSE
answer1 <- 0
i <- 1
while(!guessed){
  answer <- readline(prompt = "Write a number with 3 digits")
  numbert <- as.numeric(answer)
  if(is.na(numbert) == TRUE){
  cat(paste(answer[length(answer)], "It isn't a number", sep = " "))
  guessed <- TRUE
  }
  if(numbert %in% answer1 == TRUE){
  cat(paste(numbert, "You tried this number before", sep = " "))
  guessed <- TRUE
  }else if(numbert == numberx){
  cat(paste(numbert, "was the number, try number", i,  sep = " "))
  guessed <- TRUE
  } else {
    cat(dplyr::case_when(
    numbert > numberx      ~ paste(answer, "It is too large. This is your try", i, sep = " "),
    numbert < numberx      ~ paste(answer, "It is too small. This is your try" , i, sep = " ")
    ))
    answer1[i]<- numbert
    i <- i+1
    }
}
 

```
3.4
```{r}
n1 <- 0
n0 <- 1
x <-0
while(n1 <= 4000000){
  n1 <- n1+n0
  n0 <- n1-n0
  if(n1 %% 2 == 0){
    x <- sum(n1 + x)
  }
}
x
```

